# Generated by Django 5.2.3 on 2025-06-30 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('physical', 'Physical Abuse'), ('emotional', 'Emotional Abuse'), ('sexual', 'Sexual Abuse'), ('economic', 'Economic Abuse'), ('cyber', 'Cyber Violence'), ('stalking', 'Stalking'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='evidence_photos/')),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
